# Miniconda stuff shamelessly copied from
# https://gist.github.com/dan-blanchard/7045057
# and
# https://github.com/Jorge-C/ordination/blob/master/.travis.yml
language: python
python:
    - 2.7
env:
    - OMP_NUM_THREADS=4
before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-2.2.2-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/anaconda/bin:$PATH
    # Update conda itself
    - conda update --yes conda
    - conda install --yes pip python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib nose sphinx imaging
    - pip install -q --use-mirrors coverage coveralls pep8 sphinx-rtd-theme
install:
    - pip install .
    - make clean && make build
script:
    - make pep8-stats
    - make test
    - make coverage
    - make clean; cd doc; make linkcheck && make html && cd ..
after_success:
    - coveralls
notifications:
    email: false
