language: python
python:
    - 2.7
env:
    matrix:
        - OMP_NUM_THREADS=4
    global:
        secure: cXRXecOJ0LpQBPfl/CvrrvuDTQpN0zZ1mpGG4rs02yWRmRoykqzJpPNHBHZ1MWEHGwOP9QqXjuPTRPEHYBP4I9V/7uHgrd4rIg50gonyr0LdQFLL9QxsM6SMH/zHyma+hpWmg2k3ad6zBd0GFkaACtVlS/x2F8JG+W6TrU/oL+I=
before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-2.2.2-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/anaconda/bin:$PATH
    - conda update --yes conda
    - conda install --yes pip python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib nose
      sphinx imaging
    - pip install -q --use-mirrors coverage coveralls pep8 sphinx-rtd-theme
install:
    - pip install .
    - make clean && make build
script:
    - make pep8-stats
    - make test
    - make coverage
    - make clean; cd doc; make linkcheck && make html && cd ..
after_success:
    - coveralls
    - bash .push-docs.sh
